# Generated by Django 4.2.4 on 2023-09-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='date_order',
            new_name='date_favorite',
        ),
        migrations.AddField(
            model_name='favorites',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
